package scoutd

import (
	"bufio"
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strings"
	"text/template"
)

const yamlTemplate = `
# generated by 'scout config'
{{ if .AccountKey }}account_key: {{ .AccountKey }}{{ end }}
{{ if .HostName }}hostname: {{ .HostName }}{{ end }}
{{ if .RunDir }}run_dir: {{ .RunDir }}{{ end }}
{{ if .LogFile }}log_file: {{ .LogFile }}{{ end }}
{{ if .AgentGemBin }}agent_gem_bin: {{ .AgentGemBin }}{{ end }}
{{ if .AgentEnv }}environment: {{ .AgentEnv }}{{ end }}
{{ if .AgentRoles }}roles: {{ .AgentRoles }}{{ end }}
{{ if .AgentDataFile }}agent_data_file: {{ .AgentDataFile }}{{ end }}
{{ if .HttpProxyUrl }}http_proxy: {{ .HttpProxyUrl }}{{ end }}
{{ if .HttpsProxyUrl }}https_proxy: {{ .HttpsProxyUrl }}{{ end }}
{{ if .ReportingServerUrl }}reporting_server_url: {{ .ReportingServerUrl }}{{ end }}
`

func GenConfig(cfg ScoutConfig) {
	var buf bytes.Buffer
	t := template.Must(template.New("config").Parse(yamlTemplate))
	err := t.Execute(&buf, cfg)
	if err != nil {
		log.Fatal("Error executing template: ", err)
	}
	s := buf.String()
	if genCfgOptions.Outfile != "" {
		var out string
		if genCfgOptions.Outfile == "DEFAULT_VALUE" {
			out = cfg.ConfigFile
		} else {
			out = genCfgOptions.Outfile
		}
		if _, err := os.Stat(out); os.IsNotExist(err) {
			WriteConfig(out, s)
		} else {
			if genCfgOptions.AssumeYes {
				WriteConfig(out, s)
			} else {
				reader := bufio.NewReader(os.Stdin)
				fmt.Printf("File '%s' exists. Overwrite? [y/N] ", out)
				resp, _ := reader.ReadString('\n')
				if strings.ToUpper(string(resp[0])) == "Y" {
					WriteConfig(out, s)
				}
			}
		}
	} else {
		fmt.Printf("\n\n%s\n\n", s)
	}
}

func WriteConfig(filePath string, cfg string) {
	err := ioutil.WriteFile(filePath, []byte(cfg), 0660)
	if err != nil {
		log.Fatalf("Error writing to %s: %s", filePath, err)
	}
}
